#undef DEBOUNCE
#define DEBOUNCE 5

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "J0GoW/wONKjq"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

